### PR TITLE
759 update contact page and related pages with new photos

### LINKED ISSUE #759: Update: Contact page (and related pages) with new photos
https://drive.google.com/drive/folders/1XUCaJcB5esMQYCzTmEg7xg-52SeFFXE8

https://app.asana.com/0/1204005227675382/1204283670297106

### PR DESCRIPTION
**Pull request by Nimejandro**
## Describe your changes

Fixes: #

## Checklist before requesting review

- [x] Feature/fix PRs should add one atomic (as small as possible) feature or fix.
- [x] All code in your PR needs to have been formatted.
- [x] The merge commit title should be prefixed with the type of the PR and a colon and a space, that is "feat", "fix", "doc", "chore", or "refactor", followed by a ": ".
- [x] The merge commit body should reference at least one issue.
- [x] The code compiles and all the tests pass.

### CODE REVIEW

**Comment by Nimejandro** [comment]
To make it clear. Because the APIs dont include certain information, we partly load information from API and partly from some generated JSON after doing a excel -> csv -> json conversion of our pg file.
This code however is sustainable and will work automatically the upcoming years without needing to update barely anything.
Also removed animations because they lag too much

**Comment by Nimejandro** [comment]
image

**Review by hampfh — COMMENTED** [review]
> image

It seems like the images are overlapping the title, if this is the case in the current version could this be fixes before we merge?

**Comment by Nimejandro** [comment]
> > image
> 
> It seems like the images are overlapping the title, if this is the case in the current version could this be fixes before we merge?

This was on purpose :) But if you think it looks weird I could change it. Personally I like it and it also saves some space on the page

**Review by hampfh — APPROVED** [review]
I don't want to intervein when it comes to the design and I think the decision is yours, the reason for me asking was because my initial thought here was that there was a CSS glitch since I couldn't see the text clearly but if it is intended behavior and you have a reason for it then go ahead 👍

**Comment by hampfh** [comment]
Nice work btw, it'll be great to see the rest of the team on the page 😄 🚀

**Pull request merged**
