### PR TITLE
Update diversity page styling, add support for MDX

### PR DESCRIPTION
**Pull request by ellaklara**

### CODE REVIEW

**Comment by aclindkvist** [comment]
I cannot open the site in localhost. 

image

**Comment by ellaklara** [comment]
@aclindkvist I think you need to run `npm install` first, I've added a new package 🌟

**Comment by aclindkvist** [comment]
Oops. Thank you! brb

**Comment by aclindkvist** [comment]
I got this error message. 
image

Otherwise I was truly impressed by the outcome.

**Comment by aclindkvist** [comment]
Oh! I just noticed. In the navbar on localhost the FAQ is between sustainability and diversiry. Before we merge this, could you switch place so that sus and div is next to each other?

**Comment by aclindkvist** [comment]
image

**Comment by ellaklara** [comment]
> I got this error message.

Hmm, I can't replicate this. Maybe you could run `gatsby clean` and see if it disappears? @aclindkvist 

> Oh! I just noticed. In the navbar on localhost the FAQ is between sustainability and diversiry. Before we merge this, could you switch place so that sus and div is next to each other?

Nice catch! Fixed!

**Comment by aclindkvist** [comment]
That did the job! Thank you for the help. 
And nicely done EK. It looks amazing. Let's put it up there.

**Review by aclindkvist — APPROVED** [review]

**Pull request merged**
